@file:Suppress("INTERFACE_WITH_SUPERCLASS", "OVERRIDING_FINAL_MEMBER", "RETURN_TYPE_MISMATCH_ON_OVERRIDE", "CONFLICTING_OVERLOADS", "EXTERNAL_DELEGATION", "NESTED_CLASS_IN_EXTERNAL_INTERFACE")
@file:[JsModule("fs") JsQualifier("constants")]
package fs.constants

external var F_OK: Number = definedExternally
external var R_OK: Number = definedExternally
external var W_OK: Number = definedExternally
external var X_OK: Number = definedExternally
external var O_RDONLY: Number = definedExternally
external var O_WRONLY: Number = definedExternally
external var O_RDWR: Number = definedExternally
external var O_CREAT: Number = definedExternally
external var O_EXCL: Number = definedExternally
external var O_NOCTTY: Number = definedExternally
external var O_TRUNC: Number = definedExternally
external var O_APPEND: Number = definedExternally
external var O_DIRECTORY: Number = definedExternally
external var O_NOATIME: Number = definedExternally
external var O_NOFOLLOW: Number = definedExternally
external var O_SYNC: Number = definedExternally
external var O_SYMLINK: Number = definedExternally
external var O_DIRECT: Number = definedExternally
external var O_NONBLOCK: Number = definedExternally
external var S_IFMT: Number = definedExternally
external var S_IFREG: Number = definedExternally
external var S_IFDIR: Number = definedExternally
external var S_IFCHR: Number = definedExternally
external var S_IFBLK: Number = definedExternally
external var S_IFIFO: Number = definedExternally
external var S_IFLNK: Number = definedExternally
external var S_IFSOCK: Number = definedExternally
external var S_IRWXU: Number = definedExternally
external var S_IRUSR: Number = definedExternally
external var S_IWUSR: Number = definedExternally
external var S_IXUSR: Number = definedExternally
external var S_IRWXG: Number = definedExternally
external var S_IRGRP: Number = definedExternally
external var S_IWGRP: Number = definedExternally
external var S_IXGRP: Number = definedExternally
external var S_IRWXO: Number = definedExternally
external var S_IROTH: Number = definedExternally
external var S_IWOTH: Number = definedExternally
external var S_IXOTH: Number = definedExternally
