<!doctype html>
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <#if title??>
         <title>${title}</title>
    <#else>
        <title>documentation example</title>
    </#if>
    <meta charset="utf-8">
    <link rel="stylesheet" type="text/css" href="/static/css/styles.css">
    <link rel="stylesheet" type="text/css" href="/static/css/asciidoctor.css">
    <link rel="stylesheet" type="text/css" href="/node_modules/highlight/styles/github.css">
</head>
<body>