- language:
  - java
  - node_js
sudo: false
jdk:
  - oraclejdk8
node_js:
  - 10
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
    - $HOME/node_modules
before_script:
  - chmod +x gradlew
script:
  - ./gradlew test
  - ./gradlew jacocoJupTestReport
after_success:
  - bash <(curl -s https://codecov.io/bash)